FORMAT: 1A
HOST: https://secure.cleveranalytics.com/rest/projects/

# Metadata 2.0

Draft of new metadata for redesigned CleverAnalytics Platform

## TODO
* Is it necessary to use complete URLs for datasets, markerSelectors, markers etc.?
* Design filter metadata
* How to decide what should be searched? Addresses almost always, then all features that can be in view.
* How to save and share application state?

## PopUp

REMOVED popUp metadata.

PopUp content is automatically prepared according to feature `dataset`, selected `dashboard` and `indicator`:
* **Title and Subtitle** from `dataset.properties.featureTitle`
* **Main indicator** from currently selected `indicator`. Special position or first item in grid.
* **Other indicators grid** some other indicators in grid automatically selected from (parent) `dashboard.content.indicator`

## Project NEW [/{project}/project]

### Get project [GET]
Get default project settings. Other than `bootstrap/project`. MapOptions and ViewCategories were moved here.

+ Response 200 (application/json)

        {
            "type": "project",
            "language": "en",
            "viewCategories": [
                {
                    "name": "overview",
                    "title": "Store Performance"
                }
            ],
            "mapOptions": {
                "center": {
                    "lat": 49.8,
                    "lng": 16
                },
                "zoom": 8,
                "minZoom": 0,
                "maxZoom": 18,
                "tileLayer": "mapbox"
            }
        }


## ViewCategories [/{project}/md/viewCategories]
List all View categories.

#### TODO

+ Response 200 (application/json)

        {
            "content": [
                {
                    "id": "kdfjoi3nvs",
                    "name": "storePerformance",
                    "title": "Store Performance"
                    "type": "viewCategory",
                    "content": {
                        "icon": "iconId"
                    },
                    "links": [
                        {
                            "rel": "self",
                            "href": "/rest/projects/o3d2ov0p43msl3hf/md/viewCategories/kdfjoi3nvs"
                        }
                    ],
                }
            ],
            "links": [
                {
                    "rel": "self",
                    "href": "/rest/projects/o3d2ov0p43msl3hf/md/viewCategories?page=1"
                }
            ],
            "page": {
                "size": 20,
                "totalElements": 1,
                "totalPages": 1,
                "number": 0
            }
       }


## Datasets [/{project}/md/datasets]

### Get datasets [GET]

Get all project datasets.

#### Changes
* REMOVED `properties.includingVat` and `properties.period`
* REMOVED `properties.icon` was used for search categories. Style from
markerCollections will be used instead.
* REMOVED `properties.notFoundMessage` generic messages should be enough
* ADDED `ref.type==='vt'` new Vector Tiles dataset type
* REMOVED `properties.crs` always using 4326
* REMOVED `ref.featureKey` not necessary with DWH
* EDITED `searchBy` is removed and defined in `ref.properties` with `fullTextBoost` attribute
* ADDED `ref.subtype` dataset subtype (`geometryPolygon`, `geometryLine`,
`geometryPoint`), currently empty if dataset has no geometry
* ADDED `ref.geometry` name of corresponding vector tile dataset
* ADDED `origin` link to original project

+ Response 200 (application/json)

        {
            "content": [
                {
                   "id": "g3v3h6orb0thvd4i",
                    "name": "county-dwh",
                    "type": "dataset",
                    "title": "County",
                    "description": "Optional description of dataset",
                    "properties": {
                        "featureTitle": <Expression>,
                        "featureSubtitle": <Expression>
                    },
                    "ref": {
                        "type": "dwh",
                        "subtype": "geometryPolygon",
                        "table": "county",
                        "primaryKey": "area_code",
                        "geometry": "zsjd-vt",
                        "properties": [
                            {
                                "name": "nazev",
                                "title": "název",
                                "column": "nazev",
                                "type": "string",
                                "fullTextBoost": 8
                            },
                            {
                                "name": "kod_zsj_d",
                                "title": "kód ZSJD",
                                "column": "kod_zsj_d",
                                "type": "string"
                            },
                            {
                                "name": "x_min",
                                "column": "x_min",
                                "type": "double"
                            },
                            {
                                "name": "x_max",
                                "column": "x_max",
                                "type": "double"
                            },
                            {
                                "name": "y_min",
                                "column": "y_min",
                                "type": "double"
                            },
                            {
                                "name": "y_max",
                                "column": "y_max",
                                "type": "double"
                            }
                        ]
                    }
                },
                {
                    "id": "adc3h6orb0thvd4i",
                    "name": "store-dwh",
                    "type": "dataset",
                    "title": "My Stores",
                    "description": "Description of my stores dataset",
                    "properties": {
                        "featureTitle": <Expression>,
                        "featureSubtitle": <Expression>
                    },
                    "ref": {
                        "type": "dwh",
                        "subtype": "geometryPoint",
                        "table": "store_table",
                        "primaryKey": "store_id",
                        "properties": [
                            {
                                "name": "store_id",
                                "title": "kod pobocky",
                                "column": "id",
                                "type": "string"
                            },
                            {
                                "name": "nazev",
                                "title": "název",
                                "column": "nazev",
                                "type": "string",
                                "fullTextBoost": 4
                            },
                            {
                                "name": "lng",
                                "column": "lng",
                                "type": "longitude"
                            },
                            {
                                "name": "lat",
                                "column": "lat",
                                "type": "latitude"
                            }
                        ]
                    }
                },
                {
                    "id": "fidkjo3ij3kfcm",
                    "name": "zsjd-vt",
                    "type": "dataset",
                    "title": "Vector tiles for ZSJD",
                    "description": "Optional description of dataset",
                    "origin": "https://secure.cleveranalytics.com/rest/projects/zcoi9en758vkuuwu",
                    "properties": {
                        "zoom": {
                            "min": 5,
                            "max": 18,
                            "optimal": 16
                        }
                    },
                    "ref": {
                        "type": "vt",
                        "urlTemplate":"https://s3-eu-west-1.amazonaws.com/can-vector-tiles/zcoi9en758vkuuwu/zsjd/{z}/{x}/{y}.pbf"
                    }
                },
                {
                    "id": "oeik3jiojncs",
                    "name": "kraj_wfs"
                    "type": "dataset",
                    "title": "kraj_wfs",
                    "origin": "https://secure.cleveranalytics.com/rest/projects/zcoi9en758vkuuwu",
                    "ref": {
                        "type": "wfs",
                        "workspace": "zcoi9en758vkuuwu",
                        "layer": "kraj_wfs",
                        "primaryKey": "kod_kraj",
                        "properties": []
                    }
                }
            ],
            "links": [
                {
                    "rel": "self",
                    "href": "/rest/projects/o3d2ov0p43msl3hf/md/datasets?page=1"
                }
            }
        }
       

## Views [/{project}/md/views]

### Get views [GET]

Get all views.

#### TODO
* How to change filters from `filterGroup`?

#### Changes
* EDITED `type` is `"view"`
* REMOVED `featureCollection` moved to dashboard indicators
* REMOVED `landing` moved to `content`. Former `landing.title` must be the same as `content.title`
* REMOVED `content.grid` moved to `dashboard`
* REMOVED `content.chart`
* REMOVED `content.chartGroup`
* REMOVED `content.featureQueries` moved to `dashboard`
* REMOVED `content.measureTool` - now always available
* REMOVED `content.filters` - dropdown filter is removed (currently used for market share views)
* ADDED `content.icon` simplified `landing.icon`, no type, just image ID
* ADDED `content.description` description from `landing`
* ADDED `content.granularity` list of geometry datasets to select granularity. First is the default.
* EDITED `content.markerSelector` renamed from `fcSelector`
* ADDED `content.addressSearch` list of datasets to be searched but not displayed

+ Response 200 (application/json)

        {
            "content": [
                {
                    "id": "vfoi3jokcajkc",
                    "name": "area-overview",
                    "type": "view",
                    "title": "Revenue Overview",
                    "description": "Visualization of branch revenues across country",
                    "content": {
                        "viewCategory": "/rest/projects/$projectId/md/viewCategories?name=storePerformance",
                        "icon": "blue-1",
                        "dashboard": "/rest/projects/$projectId/md/dashboards?name=overviewDashboard",
                        "markerSelector": "/rest/projects/$projectId/md/markerSelector?name=markerSelectorStore",
                        "filterGroup": {}
                        "granularity": [
                            "zsjd-vt",
                            "okres-vt",
                            "customers"
                        ],
                         "addressSearch": [
                            "/rest/projects/$projectId/md/datasets?name=overviewDashboardaddress-points",
                            "/rest/projects/$projectId/md/datasets?name=address-streets"
                        ],
                        "mapOptions": <MapOptions>
                    }
                }
            ],
            "links": [
                {
                    "rel": "self",
                    "href": "/rest/projects/o3d2ov0p43msl3hf/md/views?page=1"
                }
            ],
            "page": {
                "size": 20,
                "totalElements": 3,
                "totalPages": 1,
                "number": 0
            }
        }

## Dashboard [/{project}/md/dashboards?name=overviewDashboard]

### Get dashboard metadata [GET]

Get dashboard metadata. Formerly known as **infoPanel**.
Now the dashboard for view should have the same capabilities
as dashboard for selected feature (marker, polygon etc.).

#### Parameters
* **name** - referenced in `view` or `markerSelectorCategory`
* **id** (optional) - if feature is selected
* **dataset** (optional) - if feature is selected

#### Changes (vs. infoPanel)
* EDITED `type` is dashboard
* REMOVED `extraFeatureCollections` not necessary in dashboard
* REMOVED `content.title` and `content.subtitle` inherited from dataset or view
* REMOVED `gridGroup`
* REMOVED `chart`
* REMOVED `chartGroup`
* REMOVED `productList`
* REMOVED `featureList`
* REMOVED `legend`
* REMOVED `radiusQuery`
* REMOVED `featureQueries` the query can be created from other content and `/indicators` resource
* REMOVED `featureCollection` Must be linked with indicator
* EDITED `content.grid` Not clickable, always just one attribute
* ADDED `content.indicator` List of clickable indicators, sometimes with catchment area

#### Indicator
Array of components. It's always possible to drill down this.
* id: indicator ID, can be found in `/metrics` resource
* fitness: type of fitness indicator visualization - `percentile` or  `trend`
* indicatorDrill: drill down indicator metadata

+ Response 200 (application/json)

        {
            "id": "ov3oif2mlkfsjas",
            "name": "overviewDashboard",
            "type": "dashboard",
            "content": {
                "indicators": [
                    {
                        "id": "revenue",
                        "fitness": "percentile",
                        "indicatorDrill": "/rest/projects/$projectId/md/indicatorDrills?name=revenueIndicatorDrill"
                    }
                ],
                "grid": [
                    {
                        "propertyId": "revenue_share",
                        "fitness": "trend"
                    }
                ]
            }
        }

## IndicatorDrill [/{project}/md/indicatorDrills?name={revenueIndicatorDrill}]

Get indicator infoPanel metadata. Formerly known as **businessGoalDetail**.
It should have the same capabilities for overview indicator and feature indicator.

### Get indicator drill metadata [GET]

#### Parameters
* **name** - referenced in `view`
* **id** - indicator id
* **featureId** (optional) - if feature is selected, potentially recursive
* **featureDataset** (optional) - if feature is selected, potentially recursive

#### TODO
* Barcharts from map categories?
* How to compute chart values, categories, formulas

#### Changes
* EDITED `type` is `indicator`
* REMOVED `featureCollection` added/updated automatically based on granularity and feature filters
* REMOVED `content.title` and `content.subtitle` replaced with former `content.businessGoal`
* REMOVED `content.businessGoal` computed automatically from parameter **propertyId**
* REMOVED `content.linkedDetails`
* REMOVED `content.filters` both slider and dropdown filters removed
* REMOVED `content.grid` moved to `blocks` or removed
* EDITED `content.legend` moved to `blocks` transformed to `histogram`
* EDITED `content.chart` moved to `blocks`
* EDITED `content.chartGroup` moved to `blocks`
* EDITED `content.productList` moved to `blocks` transformed to `ranking`
* REMOVED `extraFeatureCollections`

+ Response 200 (application/json)

        {
            "id": "ri3jckaclkanesa",
            "name": "revenueIndicatorDrill",
            "type": "indicatorDrill",
            "content": {
                "blocks": [
                    {
                        "type": "histogram"
                    },
                    {
                        "type": "ranking",
                        "size": 10
                    },
                    {
                        "type": "barchart",
                        "title": "Revenue per day of week and sex",
                        "mainSplit": "day",
                        "stackSplit": null,
                        "dualSplit": "sex",
                        "tooltip": <Expression>
                    },
                    {
                        "type": "piechart",
                        "title": "Revenue per day of week",
                        "mainSplit": "day",
                        "tooltip": <Expression>
                    },
                    {
                        "type": "grid",
                        "content": [
                            {
                                "propertyId": "revenue_share",
                                "fitness": "trend"
                            }
                        ]
                    }
                ]
            }
        }

## Indicators NEW [/{project}/md/indicators]

### Get indicators [GET]

Get all project indicators.

#### TODO
* Make sure we can automatically compute percentile, ntile, ranking, trend from each indicator metric query
* Is it possible to compute automatically values for not georeferenced records?

+ Response 200 (application/json)

        {
            "content": [
                {
                    "id": "g3v3h6orb0thvd4i",
                    "name": "revenue",
                    "type": "indicator",
                    "title": "Revenue",
                    "description": "Total annual revenue",
                    "content" : {
                        "sort": "desc",
                        "format": {
                            "type": "currency",
                            "fraction": 0
                        },
                        "distribution": "geometric",
                        "intervals": 5
                        "style": {
                            "polygon": "polygon-blue-gradient",
                            "heatmap": "heatmap-normal",
                            "point": "circle-blue-gradient-5"
                        },
                        "query": {
                            "type": "function_sum",
                            "content": [
                                {
                                    "type": "property",
                                    "value": "stores_dwh.revenue"
                                }
                            ]
                        }
                    }
                }
            ],
            "links": [
                {
                    "rel": "self",
                    "href": "/rest/projects/o3d2ov0p43msl3hf/md/indicators?page=1"
                }
            ],
            "page": {
                "size": 20,
                "totalElements": 1,
                "totalPages": 1,
                "number": 0
            }
        }

## Markers [/{project}/md/markers]

### Get all markers [GET]

Get all markers. Modified resource `featureCollections`

### TODO

* `dataset` can be inherited from `markerSelector`

### Changes
* EDITED `type` is always `marker`
* EDITED `data` Changed to `dataset` - link to dataset is enough
* EDITED `filter` Moved from data.filter, changed to default DWH filter
* REMOVED `action.hover`
* REMOVED `action.select` all params can be derived from `dataset` and `propertyId`, metadata from `infoPanel`
* REMOVED `detailInfoPanel` specified in markerSelector
* REMOVED `groupInfoPanel` should have the same content as `infoPanel`
* EDITED `defaultStyle` replaced with `style` -- ID of predefined style

+ Response 200 (application/json)

        {
            "content": [
                {
                    "id": "st3fdkwlafdsl",
                    "name": "stores-blue",
                    "type": "marker",
                    "content": {
                        "dataset": "/rest/projects/$projectId/md/datasets?name=store-dwh"
                        "filter": [
                            {
                                "property": "storetype",
                                "value": "blue",
                                "operator": "eq"
                            }
                        ],
                        "style": "marker-blue"
                    }
                },
                {
                    "id": "pk3kljcalksaf",
                    "name": "stores-pink",
                    "type": "marker",
                    "content": {
                        "dataset": "/rest/projects/$projectId/md/datasets?name=store-dwh",
                        "filter": [
                            {
                                "property": "storetype",
                                "value": "pink",
                                "operator": "eq"
                            }
                        ],
                        "style": "marker-pink"
                    }
                }
            ],
            "links": [
                {
                    "rel": "self",
                    "href": "/rest/projects/o3d2ov0p43msl3hf/md/markers?page=1"
                }
            ],
            "page": {
                "size": 20,
                "totalElements": 2,
                "totalPages": 1,
                "number": 0
            }
        }

## MarkerSelector [/{project}/md/markerSelectors?name={markerSelectorOverview}]

### Get markerSelector [GET]

Get markerSelector. This was previously fcSelector, but it can show only marker layers now.

### Changes
* EDITED `type` is always `markerSelector`

+ Response 200 (application/json)

        {
            "content": [
                {
                    "id": "ms8j8rjfdkaj",
                    "type": "markerSelector",
                    "content": {
                        "dataset": "/rest/projects/$projectId/md/datasets?name=store-dwh",
                        "dashboard": "/rest/projects/$projectId/md/dashboards?name=storeDashboard",
                        "layers": [
                            {
                                "marker": "/rest/projects/$projectId/md/markers?name=stores-blue",
                                "visible": true
                            },
                            {
                                "marker": "/rest/projects/$projectId/md/markers?name=stores-pink",
                                "visible": true
                            }
                        ]
                    }
                },
                {
                    "id": "ms8j8rjfdkaj",
                    "type": "markerSelector",
                    "content": {
                        "dataset": "/rest/projects/$projectId/md/datasets?name=store-dwh",
                        "dashboard": "/rest/projects/$projectId/md/dashboards?name=atmDashboard",
                        "layers": [
                            {
                                "marker": "/rest/projects/$projectId/md/markers?name=atm-blue",
                                "visible": false,
                                "addOnExpand": true
                            },
                            {
                                "marker": "/rest/projects/$projectId/md/markers?name=atm-pink",
                                "visible": false,
                                "addOnExpand": false
                            }
                        ]
                    }
                }
            ],
            "links": [
                {
                    "rel": "self",
                    "href": "/rest/projects/o3d2ov0p43msl3hf/md/markerSelectors?page=1"
                }
            ],
            "page": {
                "size": 20,
                "totalElements": 2,
                "totalPages": 1,
                "number": 0
            }
        }